name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.name kec08
          git config user.email kec4489@naver.com
          git add -A .
          git commit -m "generated" || echo "Nothing to commit"
          git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
